server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true # shardingsphere  一个实体类对应两张表，覆盖
  mvc: #  swagger引用   Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser Springfox 使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
    pathmatch:
      matching-strategy: ant_path_matcher
  task:   #ThreadPoolTaskExecutor配置
    execution:
      pool:
        core-size: 6 # 核心线程池数
        max-size: 10 # 最大线程池数
        queue-capacity: 50 # 任务队列的容量
        keep-alive: 600 # 非核心线程的存活时间
      thread-name-prefix: stock-task- # 线程池的前缀名称
  shardingsphere:
    datasource:
      names: hnmarket0,hnmarket1
      hnmarket0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hnmarket0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456
      hnmarket1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hnmarket1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: smarket
          algorithm-expression: hnmarket$->{smarket % 2}
      tables:
        mk_indiv_day:
          actual-data-nodes: hnmarket$->{0..1}.mk_indiv_day$->{0..19}
          table-strategy:
#            inline:
#              sharding-column: scode_num
#              algorithm-expression: mk_indiv_day$->{scode_num % 20}
            standard: #自定义分片规则类
              sharding-column: scode
              precise-algorithm-class-name: com.hn.market.common.utils.ShardingTableKeyUtils
#          key-generator:
#            #主键id 生成策略  SNOWFLAKE
#            column: tenant_id
#            type: SNOWFLAKE
    props:
      sql:
        show: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true