server:
  port: 8080

spring:
  application:
    name: hn-market
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  task:   #ThreadPoolTaskExecutor配置
    execution:
      pool:
        core-size: 6 # 核心线程池数
        max-size: 10 # 最大线程池数
        queue-capacity: 100 # 任务队列的容量
        keep-alive: 60 # 非核心线程的存活时间
      thread-name-prefix: stock-task- # 线程池的前缀名称

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout

