spring:
  datasource:
    url: jdbc:mysql://db:3306/hnmarket?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&&rewriteBatchedStatements=true
    username: root
    password: 123456

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info