spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hnmarket?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456

logging:
  level:
    root: info
    com.macro.mall: debug